language: ruby
services:
- docker
before_install:
- docker build -t helloworld .
script:
- docker run helloworld rspec
deploy:
  provider: heroku
  app: hello-world-app-staging
  api_key:
    secure: vgBjENvkrX48V/EgB80ZSoKg7wwwZcqw8DcxaMlgHzxrILqxGVhyvAit6DxV/+RKAFk7QeyHnvxLFNsGsKQh/U4ikVKkPmNPBJhYpsWMza64m1Wj10pqxdKLRaVxjCqnbnDdb8rcRuycJoPu8xcCz8AmUMUPsbBVIcMlYSU2yVGng5kNxKaeDnVsueGEk6P0thfbFguuDUEEVJpNJZzyj0oaBwxqYdyE2phHcptDU+gNhlI/5vGZWsk3v0ru96EoFH79f/AbaYK8oMLDg00KJWyLTFIdi3UUrzz+4Ghsoa1krxZQkdK1bjPcHo620P3GWW9Gu71Luqr+TgRwZg2yF4gXGvJBqcRehhlj2WQrwyeEmNjXU8ll0oi94zQL7APEtQ8pQTPSreqSM41iVlvDu1fXwLt6oIT98VnNQHDBLUIQIBTLxX8DUAM9kyNPyVQms++wtJlpjzUbabqymtr1jZTpWyaGnYoFo9SgCYp3JKMgntwTcXX0q4hVtuqgVfbXr1pNTL6NGWjrGq0kcgYueXmq7ana5F/eBDV3Dz68epV6ebBb5r9sCe0sEzpdUGJ8Aq2WL2znZscsJGM3tuprq2vet2e+JX15BRLlA1rewijvpZ9mur97ii+K+pHg86Q9ofPdhpDTi3dsmM/EZKdNCwlV662CWe2Rd5Qubvl6ztA=
  on: master
